### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by MaestroJurko** [danielgindi/node-optimize#2]
I have a server folder, in this server folder I multiple folders, which contain modules, that are used around the project.

```
server/
      app.js
      documents
           one.js
      general
           two.js
```

How would you use it then?

**Comment by danielgindi** [comment]
If `app.js` is your main file - then just point it to `app.js`, it will do the rest!
Of course if there are files that are supposed to be excluded you can use the special option `ignore`.

Look at the sample in the README, and you may also want to check `grunt-node-optimize` which runs this as a Grunt task.

**Comment by MaestroJurko** [comment]
Yes, app.js is my main file, but not all code is concated and minimised in one file.

I am getting this:

> Ignoring complex require statement in:
>   file      : /vagrant/server/api-suit/suit.js
>   statement : require('./' + module)
>   You may want to add that file to options.include.

I added it to include, but still getting this issue.

**Comment by danielgindi** [comment]
The fact that you are getting the warning is ok; It just means that the parser recognized a complex require statement. It does not know what to do with it in "compile" time, but it can handle it in runtime! As long as the file gets included correctly.

The `include` option gets an array of files to include - just make sure that the paths are correct.

If you get a bigger file size with the `include` option, then you are on the right track!

**Comment by MaestroJurko** [comment]
The file gets included in the minimised code, but required modules are not.

suit.js

```
var modules = ['jobs', 'actions', 'logs', 'runs', 'results', 'history', 'launcher', 'shredder', 'initialise'];

module.exports = modules.map(function (module) {
    return require('./' + module);
});


```

**Comment by danielgindi** [comment]
I see now that there's one issue where in those complex situations the `require` call sometimes do not get replaced with the `__FAKE_REQUIRE__`.
Hold on- pushing a fix in 5 mins.

**Comment by danielgindi** [comment]
I've created a sample for your situation, attached.
Run `node optimize` and it will optimize `app.js`

[sample.zip](https://github.com/danielgindi/node-optimize/files/108042/sample.zip)

Tested, and works with `node-optimize` 1.2.1 :-)

**Comment by MaestroJurko** [comment]
THX
