### ISSUE TITLE
Segmentation Fault Error on Grunt Build

### ISSUE THREAD

**Issue by swateek** [danielgindi/node-optimize#3]
I have used Yeoman Fullstack Genrator for my application and was trying to package it into a binary using this library.

I get a "Segmentation Fault" on starting "grunt build".

Not sure where am I getting this error from, no further logs are printed even with a 
"-v" option. Where should I look for to solve this error?

**Comment by danielgindi** [comment]
Segmentation Fault means that node has crashed painfully (very rare) or that there's a big memory problem.
I don't see a reason for filling the memory in such great amounts- so you'll need to play around with it a little.
See if there's a complexity in your project that is not taken into account by the library.

Also if you are packaging `node_modules` too, you might want to try Browserify - with `builtins` turned off. It has become quite a standard, and some modules supply special instructions on how to package "for the browser", or in fact any standalone environment.
